icons = "awesome"

[theme]
name = "space-villain"
[theme.overrides]
idle_bg = "#123456"
# idle_fg = "#abcdef"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
interface_name_exclude = [".*kdeconnect.*", "mpd"]

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "{icon}{used}/{total} {unit}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "{utilization}"


[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

# [[block]]
# block = "xrandr"
# icons = true
# resolution = true
# interval = 2

[[block]]
block = "sound"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time}"
