icons = "awesome"

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "music"
buttons = ["play", "next"]
interface_name_exclude = [".*kdeconnect.*", "mpd"]

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "used"
unit = "GiB"
format = "{icon}{used}/{total} {unit}"

# [[block]]
# block = "disk_space"
# path = "/"
# alias = "/"
# info_type = "available"
# unit = "GB"
# interval = 20

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time}"
